/* AteliersBook document, sales, currency, reminder and access extensions */
(()=>{
  const currencyKey='ateliersbook-currency';let currency=localStorage.getItem(currencyKey)||'GHS';const symbols={GHS:'GH₵',USD:'$',EUR:'€',GBP:'£',NGN:'₦',KES:'KSh',ZAR:'R'};const fmt=n=>(symbols[currency]||currency+' ')+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  const profile=$('brandForm');profile.insertAdjacentHTML('beforeend','<label style="display:block;margin-top:14px">Working currency<select id="workingCurrency"><option value="GHS">Ghana cedi (GH₵)</option><option value="USD">US dollar ($)</option><option value="EUR">Euro (€)</option><option value="GBP">British pound (£)</option><option value="NGN">Nigerian naira (₦)</option><option value="KES">Kenyan shilling (KSh)</option><option value="ZAR">South African rand (R)</option></select></label>');$('workingCurrency').value=currency;$('workingCurrency').onchange=()=>{currency=$('workingCurrency').value;localStorage.setItem(currencyKey,currency);alert('Currency saved for new documents and sales.');};
  function pdf(title,lines){const P=window.jspdf?.jsPDF;if(!P)return alert('Document tool is loading. Please try again shortly.');const d=new P();let y=18;d.setFontSize(19);d.text(title,15,y);y=33;d.setFontSize(11);lines.forEach(line=>d.splitTextToSize(String(line),175).forEach(text=>{if(y>280){d.addPage();y=18}d.text(text,15,y);y+=7}));d.save(title.replace(/[^a-z0-9]/gi,'-').toLowerCase()+'.pdf');}
  window.downloadInvoice=id=>{const o=db.orders.find(x=>x.id===id),c=db.clients.find(x=>x.id===o?.client);if(!o)return;pdf('Invoice',[`Client: ${c?.name||''}`,`Address: ${c?.address||'—'}`,`Order: ${o.description}`,`Invoice date: ${o.orderDate||'—'}`,`Delivery date: ${o.delivery||'—'}`,`Total due: ${fmt(o.price)}`,`Deposit: ${fmt(o.deposit)}`,`Full payment: ${fmt(o.fullPayment)}`,`Balance: ${fmt(Math.max(0,o.price-o.deposit-o.fullPayment))}`]);};
  window.downloadReceipt=id=>{const o=db.orders.find(x=>x.id===id),c=db.clients.find(x=>x.id===o?.client);if(!o)return;pdf('Payment receipt',[`Received from: ${c?.name||''}`,`Order: ${o.description}`,`Deposit received: ${fmt(o.deposit)}`,`Full payment received: ${fmt(o.fullPayment)}`,`Total received: ${fmt(Number(o.deposit||0)+Number(o.fullPayment||0))}`,`Status: ${o.fullPaymentMade?'Paid in full':'Part payment'}`]);};
  window.downloadMeasurements=id=>{const c=db.clients.find(x=>x.id===id);if(!c)return;pdf('Client measurement sheet',[`Client: ${c.name}`,`Phone: ${c.phone||'—'}`,`Address: ${c.address||'—'}`,...measurementKeys.map(k=>`${k.replace(/([A-Z])/g,' $1')}: ${c[k]||'—'} cm`)]);};
  const oldDetail=detail;detail=()=>{oldDetail();const c=db.clients.find(x=>x.id===selected);if(!c)return;const actions=$('clientDetail').querySelector('.actions');if(actions){const b=document.createElement('button');b.className='button secondary';b.textContent='Measurement PDF';b.onclick=()=>downloadMeasurements(c.id);actions.append(b);}const rows=$('clientDetail').querySelectorAll('.row'),orders=db.orders.filter(o=>o.client===c.id);orders.forEach((o,i)=>{if(!rows[i])return;['Invoice','Receipt'].forEach(kind=>{const b=document.createElement('button');b.className='button secondary';b.style.cssText='padding:6px 8px;font-size:11px';b.textContent=kind;b.onclick=()=>kind==='Invoice'?downloadInvoice(o.id):downloadReceipt(o.id);rows[i].append(b);});});};
  const tab=document.createElement('button');tab.className='tab';tab.dataset.view='sales';tab.textContent='Ready-to-wear';document.querySelector('.tabs').append(tab);const view=document.createElement('section');view.id='sales';view.className='view';view.innerHTML='<div class="heading"><div><h1>Ready-to-wear & other sales</h1><p>Record income and expenditure for ready-made clothes, accessories and other items.</p></div><button class="button primary" id="addProductSale">+ Add sale</button></div><div class="stats"><div class="stat"><b id="saleIncome">GH₵0.00</b><span>Income</span></div><div class="stat"><b id="saleCost">GH₵0.00</b><span>Expenditure</span></div><div class="stat"><b id="saleProfit">GH₵0.00</b><span>Profit</span></div></div><div class="panel"><div class="panel-head"><h2>Sales register</h2></div><div id="saleRegister"></div></div>';$('profile').after(view);tab.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');view.classList.add('active');drawSales();};
  let dialog=document.createElement('dialog');dialog.innerHTML='<form class="modal" id="productSaleForm"><div class="modal-top"><h2>Add sale</h2><button type="button" class="close" onclick="this.closest(\'dialog\').close()">×</button></div><div class="fields"><label>Item name<input id="productName" required></label><label>Type<select id="productType"><option>Ready-to-wear</option><option>Accessory</option><option>Other</option></select></label><label>Income / selling price<input id="productPrice" type="number" min="0" step=".01" required></label><label>Expenditure / cost<input id="productCost" type="number" min="0" step=".01" required></label><label>Quantity<input id="productQty" type="number" min="1" value="1" required></label><label>Date<input id="productDate" type="date" required></label></div><div class="foot"><button class="button primary">Save sale</button></div></form>';document.body.append(dialog);db.sales=db.sales||[];function drawSales(){const a=db.sales,inc=a.reduce((s,x)=>s+x.price*x.qty,0),cost=a.reduce((s,x)=>s+x.cost*x.qty,0);$('saleIncome').textContent=fmt(inc);$('saleCost').textContent=fmt(cost);$('saleProfit').textContent=fmt(inc-cost);$('saleRegister').innerHTML=a.length?'<table><tr><th>Item</th><th>Type</th><th>Income</th><th>Cost</th><th>Profit</th></tr>'+a.map(x=>`<tr><td><b>${x.name}</b><small>${x.date} · ${x.qty} unit(s)</small></td><td>${x.type}</td><td>${fmt(x.price*x.qty)}</td><td>${fmt(x.cost*x.qty)}</td><td class="profit">${fmt((x.price-x.cost)*x.qty)}</td></tr>`).join('')+'</table>':'<div class="empty">No ready-to-wear or other sales recorded.</div>';}$('addProductSale').onclick=()=>{$('productSaleForm').reset();$('productQty').value=1;$('productDate').value=new Date().toISOString().slice(0,10);dialog.showModal();};$('productSaleForm').onsubmit=async e=>{e.preventDefault();const sale={name:$('productName').value,type:$('productType').value,price:+$('productPrice').value,cost:+$('productCost').value,qty:+$('productQty').value,date:$('productDate').value};db.sales.unshift(sale);localStorage.setItem(K,JSON.stringify(db));drawSales();try{if(currentUser)await firebase.firestore().collection('ateliersbook').doc(currentUser.uid).collection('finance').doc('sales').set({items:db.sales});dialog.close();}catch(err){db.sales=db.sales.filter(x=>x!==sale);localStorage.setItem(K,JSON.stringify(db));drawSales();alert('Sale was not saved to Firebase: '+err.message);}};let stopSalesSync=null;firebase.auth().onAuthStateChanged(u=>{if(stopSalesSync){stopSalesSync();stopSalesSync=null;}if(u)stopSalesSync=firebase.firestore().collection('ateliersbook').doc(u.uid).collection('finance').doc('sales').onSnapshot(s=>{if(s.exists){db.sales=s.data().items||[];localStorage.setItem(K,JSON.stringify(db));drawSales();}},err=>alert('Sales could not sync: '+err.message));});
  const reminderTab=document.createElement('button');reminderTab.className='tab';reminderTab.dataset.view='reminders';reminderTab.textContent='Reminders';document.querySelector('.tabs').append(reminderTab);const reminderView=document.createElement('section');reminderView.id='reminders';reminderView.className='view';reminderView.innerHTML='<div class="heading"><div><h1>Order reminders</h1><p>Keep track of fittings, delivery dates and unpaid orders.</p></div><button class="button secondary" id="refreshReminders">Refresh</button></div><div id="reminderList"></div>';view.after(reminderView);reminderTab.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));reminderTab.classList.add('active');reminderView.classList.add('active');drawReminders();};
  const dayStart=date=>new Date(date+'T00:00');function drawReminders(){const now=new Date();now.setHours(0,0,0,0);const open=db.orders.filter(o=>o.closure!=='Closed');const entries=[];open.forEach(o=>{const c=db.clients.find(x=>x.id===o.client);const label=c?.name||'Client';if(o.fittingDate){const days=Math.ceil((dayStart(o.fittingDate)-now)/86400000);if(days<0)entries.push({when:'Overdue fitting',tone:'danger',text:`${label} — ${o.description}`,date:o.fittingDate});else if(days===0)entries.push({when:'Fitting today',tone:'warn',text:`${label} — ${o.description}`,date:o.fittingDate});else if(days<=7)entries.push({when:`Fitting in ${days} day${days===1?'':'s'}`,tone:'info',text:`${label} — ${o.description}`,date:o.fittingDate});}if(o.delivery){const days=Math.ceil((dayStart(o.delivery)-now)/86400000);if(days<0)entries.push({when:'Overdue delivery',tone:'danger',text:`${label} — ${o.description}`,date:o.delivery});else if(days<=7)entries.push({when:days===0?'Delivery today':`Delivery in ${days} day${days===1?'':'s'}`,tone:'warn',text:`${label} — ${o.description}`,date:o.delivery});}if(Number(o.price||0)>Number(o.deposit||0)+Number(o.fullPayment||0))entries.push({when:'Payment outstanding',tone:'info',text:`${label} — ${o.description} (${fmt(Number(o.price||0)-Number(o.deposit||0)-Number(o.fullPayment||0))})`,date:o.delivery||o.orderDate||'—'});});entries.sort((a,b)=>String(a.date).localeCompare(String(b.date)));$('reminderList').innerHTML=entries.length?'<div class="panel"><div class="panel-head"><h2>'+entries.length+' active reminder'+(entries.length===1?'':'s')+'</h2></div>'+entries.map(r=>`<div class="row"><div><b>${r.when}</b><small>${r.text}</small></div><span class="status ${r.tone==='danger'?'closed':''}">${r.date}</span></div>`).join('')+'</div>':'<div class="empty">You are all caught up — no active order reminders.</div>';return entries;}$('refreshReminders').onclick=drawReminders;
  function remind(){const due=drawReminders().filter(r=>r.when==='Fitting today'||r.when.startsWith('Fitting in 1')||r.when.startsWith('Fitting in 2'));if(due.length&&'Notification'in window&&Notification.permission==='granted')new Notification('AteliersBook reminder',{body:`${due.length} fitting reminder${due.length===1?'':'s'} need attention.`});}if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();setInterval(remind,1800000);remind();drawSales();
})();

/* Ready-to-wear product photos: 5 MB limit, deletion and 30-day cleanup */
(()=>{
  const maxPhotoBytes=5*1024*1024;
  const saleForm=$('productSaleForm');
  const dateField=$('productDate').closest('label');
  dateField.insertAdjacentHTML('afterend','<label class="full">Item photo <input id="productImage" type="file" accept="image/*"><small>Optional. Maximum size: 5 MB. Photos are removed after 30 days.</small></label>');
  const salesTab=document.querySelector('.tab[data-view="sales"]');
  const salesDialog=saleForm.closest('dialog');
  const storeSales=async()=>{localStorage.setItem(K,JSON.stringify(db));if(currentUser)await firebase.firestore().collection('ateliersbook').doc(currentUser.uid).collection('finance').doc('sales').set({items:db.sales});};
  function renderSalesWithPhotos(){const sales=db.sales||[],income=sales.reduce((total,sale)=>total+Number(sale.price||0)*Number(sale.qty||0),0),cost=sales.reduce((total,sale)=>total+Number(sale.cost||0)*Number(sale.qty||0),0);$('saleIncome').textContent=fmt(income);$('saleCost').textContent=fmt(cost);$('saleProfit').textContent=fmt(income-cost);$('saleRegister').innerHTML=sales.length?'<table><tr><th>Item</th><th>Type</th><th>Income</th><th>Cost</th><th>Profit</th></tr>'+sales.map(sale=>`<tr><td style="min-width:190px">${sale.imageUrl?`<img src="${sale.imageUrl}" alt="${sale.name}" style="width:58px;height:58px;object-fit:cover;border-radius:10px;float:left;margin:0 10px 6px 0">`:''}<b>${sale.name}</b><small>${sale.date} · ${sale.qty} unit(s)</small>${sale.imageUrl?`<button class="button secondary" style="padding:4px 7px;font-size:10px;margin-top:5px" onclick="deleteSalePhoto('${sale.id}')">Delete photo</button>`:''}</td><td>${sale.type}</td><td>${fmt(Number(sale.price||0)*Number(sale.qty||0))}</td><td>${fmt(Number(sale.cost||0)*Number(sale.qty||0))}</td><td class="profit">${fmt((Number(sale.price||0)-Number(sale.cost||0))*Number(sale.qty||0))}</td></tr>`).join('')+'</table>':'<div class="empty">No ready-to-wear or other sales recorded.</div>';}
  window.deleteSalePhoto=async id=>{const sale=(db.sales||[]).find(item=>item.id===id);if(!sale||!confirm('Delete this item photo?'))return;try{if(currentUser&&sale.imagePath)await firebase.storage().ref(sale.imagePath).delete();sale.imageUrl='';sale.imagePath='';sale.imageAddedAt='';await storeSales();renderSalesWithPhotos();}catch(err){alert('Photo could not be deleted: '+err.message);}};
  async function removeExpiredPhotos(){if(!currentUser)return;const cutoff=Date.now()-30*24*60*60*1000;const expired=(db.sales||[]).filter(sale=>sale.imagePath&&sale.imageAddedAt&&new Date(sale.imageAddedAt).getTime()<=cutoff);if(!expired.length)return;for(const sale of expired){try{await firebase.storage().ref(sale.imagePath).delete();}catch(err){if(err.code!=='storage/object-not-found')continue;}sale.imageUrl='';sale.imagePath='';sale.imageAddedAt='';}await storeSales();renderSalesWithPhotos();}
  saleForm.onsubmit=async event=>{event.preventDefault();const file=$('productImage').files[0];if(file&&file.size>maxPhotoBytes){alert('Please choose an image smaller than 5 MB.');return;}if(file&&!currentUser){alert('Please sign in before adding an item photo.');return;}const sale={id:crypto.randomUUID(),name:$('productName').value,type:$('productType').value,price:+$('productPrice').value,cost:+$('productCost').value,qty:+$('productQty').value,date:$('productDate').value,imageUrl:'',imagePath:'',imageAddedAt:''};try{if(file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`ateliersbook/${currentUser.uid}/sales/${sale.id}/${safeName}`,ref=firebase.storage().ref(path);await ref.put(file);sale.imageUrl=await ref.getDownloadURL();sale.imagePath=path;sale.imageAddedAt=new Date().toISOString();}db.sales=db.sales||[];db.sales.unshift(sale);await storeSales();salesDialog.close();renderSalesWithPhotos();}catch(err){alert('Sale was not saved: '+err.message);}};
  let editingSaleId=null;
  window.editSale=id=>{const sale=(db.sales||[]).find(item=>item.id===id);if(!sale)return;editingSaleId=id;$('productName').value=sale.name||'';$('productType').value=sale.type||'Ready-to-wear';$('productPrice').value=sale.price??'';$('productCost').value=sale.cost??'';$('productQty').value=sale.qty??1;$('productDate').value=sale.date||'';$('productImage').value='';saleForm.querySelector('h2').textContent='Edit sale';salesDialog.showModal();};
  $('addProductSale').onclick=()=>{editingSaleId=null;saleForm.reset();$('productQty').value=1;$('productDate').value=new Date().toISOString().slice(0,10);saleForm.querySelector('h2').textContent='Add sale';salesDialog.showModal();};
  const ensureSaleIds=()=>{let changed=false;db.sales=(db.sales||[]).map(sale=>{if(sale.id)return sale;changed=true;return {...sale,id:crypto.randomUUID()};});if(changed){localStorage.setItem(K,JSON.stringify(db));if(currentUser)firebase.firestore().collection('ateliersbook').doc(currentUser.uid).collection('finance').doc('sales').set({items:db.sales}).catch(()=>{});}};
  renderSalesWithPhotos=()=>{ensureSaleIds();const sales=db.sales||[],income=sales.reduce((total,sale)=>total+Number(sale.price||0)*Number(sale.qty||0),0),cost=sales.reduce((total,sale)=>total+Number(sale.cost||0)*Number(sale.qty||0),0);$('saleIncome').textContent=fmt(income);$('saleCost').textContent=fmt(cost);$('saleProfit').textContent=fmt(income-cost);$('saleRegister').innerHTML=sales.length?'<table><tr><th>Item</th><th>Type</th><th>Income</th><th>Cost</th><th>Profit</th></tr>'+sales.map(sale=>`<tr><td style="min-width:190px">${sale.imageUrl?`<img src="${sale.imageUrl}" alt="${sale.name}" style="width:58px;height:58px;object-fit:cover;border-radius:10px;float:left;margin:0 10px 6px 0">`:''}<b>${sale.name}</b><small>${sale.date} · ${sale.qty} unit(s)</small><div><button class="button secondary" style="padding:4px 7px;font-size:10px;margin-top:5px" onclick="editSale('${sale.id}')">Edit</button>${sale.imageUrl?` <button class="button secondary" style="padding:4px 7px;font-size:10px;margin-top:5px" onclick="deleteSalePhoto('${sale.id}')">Delete photo</button>`:''}</div></td><td>${sale.type}</td><td>${fmt(Number(sale.price||0)*Number(sale.qty||0))}</td><td>${fmt(Number(sale.cost||0)*Number(sale.qty||0))}</td><td class="profit">${fmt((Number(sale.price||0)-Number(sale.cost||0))*Number(sale.qty||0))}</td></tr>`).join('')+'</table>':'<div class="empty">No ready-to-wear or other sales recorded.</div>';};
  saleForm.onsubmit=async event=>{event.preventDefault();const file=$('productImage').files[0];if(file&&file.size>maxPhotoBytes){alert('Please choose an image smaller than 5 MB.');return;}if(file&&!currentUser){alert('Please sign in before adding an item photo.');return;}const existing=(db.sales||[]).find(item=>item.id===editingSaleId),sale=existing||{id:crypto.randomUUID(),imageUrl:'',imagePath:'',imageAddedAt:''};try{Object.assign(sale,{name:$('productName').value,type:$('productType').value,price:+$('productPrice').value,cost:+$('productCost').value,qty:+$('productQty').value,date:$('productDate').value});if(file){const oldPath=sale.imagePath,safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`ateliersbook/${currentUser.uid}/sales/${sale.id}/${safeName}`,ref=firebase.storage().ref(path);await ref.put(file);sale.imageUrl=await ref.getDownloadURL();sale.imagePath=path;sale.imageAddedAt=new Date().toISOString();if(oldPath&&oldPath!==path)firebase.storage().ref(oldPath).delete().catch(()=>{});}if(!existing){db.sales=db.sales||[];db.sales.unshift(sale);}await storeSales();editingSaleId=null;salesDialog.close();renderSalesWithPhotos();}catch(err){alert('Sale was not saved: '+err.message);}};
  salesTab.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(item=>item.classList.remove('active'));salesTab.classList.add('active');$('sales').classList.add('active');renderSalesWithPhotos();};
  let photoSalesSyncStop=null;firebase.auth().onAuthStateChanged(async user=>{if(photoSalesSyncStop){photoSalesSyncStop();photoSalesSyncStop=null;}if(user){photoSalesSyncStop=firebase.firestore().collection('ateliersbook').doc(user.uid).collection('finance').doc('sales').onSnapshot(snapshot=>{if(snapshot.exists){db.sales=snapshot.data().items||[];localStorage.setItem(K,JSON.stringify(db));renderSalesWithPhotos();}});await removeExpiredPhotos();renderSalesWithPhotos();}});
  renderSalesWithPhotos();
})();
